/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.rivetlogic.assetmanagement.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetLocation service. Represents a row in the &quot;rivetlogic_AssetLocation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.assetmanagement.model.impl.AssetLocationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.assetmanagement.model.impl.AssetLocationImpl}.
 * </p>
 *
 * @author Manrique Varela
 * @see AssetLocation
 * @see com.rivetlogic.assetmanagement.model.impl.AssetLocationImpl
 * @see com.rivetlogic.assetmanagement.model.impl.AssetLocationModelImpl
 * @generated
 */
public interface AssetLocationModel extends BaseModel<AssetLocation> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset location model instance should use the {@link AssetLocation} interface instead.
	 */

	/**
	 * Returns the primary key of this asset location.
	 *
	 * @return the primary key of this asset location
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset location.
	 *
	 * @param primaryKey the primary key of this asset location
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this asset location.
	 *
	 * @return the uuid of this asset location
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this asset location.
	 *
	 * @param uuid the uuid of this asset location
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the asset location ID of this asset location.
	 *
	 * @return the asset location ID of this asset location
	 */
	public long getAssetLocationId();

	/**
	 * Sets the asset location ID of this asset location.
	 *
	 * @param assetLocationId the asset location ID of this asset location
	 */
	public void setAssetLocationId(long assetLocationId);

	/**
	 * Returns the group ID of this asset location.
	 *
	 * @return the group ID of this asset location
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this asset location.
	 *
	 * @param groupId the group ID of this asset location
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this asset location.
	 *
	 * @return the company ID of this asset location
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset location.
	 *
	 * @param companyId the company ID of this asset location
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this asset location.
	 *
	 * @return the user ID of this asset location
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this asset location.
	 *
	 * @param userId the user ID of this asset location
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this asset location.
	 *
	 * @return the user uuid of this asset location
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this asset location.
	 *
	 * @param userUuid the user uuid of this asset location
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this asset location.
	 *
	 * @return the user name of this asset location
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this asset location.
	 *
	 * @param userName the user name of this asset location
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this asset location.
	 *
	 * @return the create date of this asset location
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset location.
	 *
	 * @param createDate the create date of this asset location
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the name of this asset location.
	 *
	 * @return the name of this asset location
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this asset location.
	 *
	 * @param name the name of this asset location
	 */
	public void setName(String name);

	/**
	 * Returns the description of this asset location.
	 *
	 * @return the description of this asset location
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this asset location.
	 *
	 * @param description the description of this asset location
	 */
	public void setDescription(String description);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AssetLocation assetLocation);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AssetLocation> toCacheModel();

	@Override
	public AssetLocation toEscapedModel();

	@Override
	public AssetLocation toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}