/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.rivetlogic.assetmanagement.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AssetMessage service. Represents a row in the &quot;rivetlogic_AssetMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.rivetlogic.assetmanagement.model.impl.AssetMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.rivetlogic.assetmanagement.model.impl.AssetMessageImpl}.
 * </p>
 *
 * @author Manrique Varela
 * @see AssetMessage
 * @see com.rivetlogic.assetmanagement.model.impl.AssetMessageImpl
 * @see com.rivetlogic.assetmanagement.model.impl.AssetMessageModelImpl
 * @generated
 */
public interface AssetMessageModel extends BaseModel<AssetMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a asset message model instance should use the {@link AssetMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this asset message.
	 *
	 * @return the primary key of this asset message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this asset message.
	 *
	 * @param primaryKey the primary key of this asset message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this asset message.
	 *
	 * @return the uuid of this asset message
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this asset message.
	 *
	 * @param uuid the uuid of this asset message
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the asset message ID of this asset message.
	 *
	 * @return the asset message ID of this asset message
	 */
	public long getAssetMessageId();

	/**
	 * Sets the asset message ID of this asset message.
	 *
	 * @param assetMessageId the asset message ID of this asset message
	 */
	public void setAssetMessageId(long assetMessageId);

	/**
	 * Returns the group ID of this asset message.
	 *
	 * @return the group ID of this asset message
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this asset message.
	 *
	 * @param groupId the group ID of this asset message
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this asset message.
	 *
	 * @return the company ID of this asset message
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this asset message.
	 *
	 * @param companyId the company ID of this asset message
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this asset message.
	 *
	 * @return the create date of this asset message
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this asset message.
	 *
	 * @param createDate the create date of this asset message
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the asset ID of this asset message.
	 *
	 * @return the asset ID of this asset message
	 */
	public long getAssetId();

	/**
	 * Sets the asset ID of this asset message.
	 *
	 * @param assetId the asset ID of this asset message
	 */
	public void setAssetId(long assetId);

	/**
	 * Returns the from user ID of this asset message.
	 *
	 * @return the from user ID of this asset message
	 */
	public long getFromUserId();

	/**
	 * Sets the from user ID of this asset message.
	 *
	 * @param fromUserId the from user ID of this asset message
	 */
	public void setFromUserId(long fromUserId);

	/**
	 * Returns the from user uuid of this asset message.
	 *
	 * @return the from user uuid of this asset message
	 * @throws SystemException if a system exception occurred
	 */
	public String getFromUserUuid() throws SystemException;

	/**
	 * Sets the from user uuid of this asset message.
	 *
	 * @param fromUserUuid the from user uuid of this asset message
	 */
	public void setFromUserUuid(String fromUserUuid);

	/**
	 * Returns the to user ID of this asset message.
	 *
	 * @return the to user ID of this asset message
	 */
	public long getToUserId();

	/**
	 * Sets the to user ID of this asset message.
	 *
	 * @param toUserId the to user ID of this asset message
	 */
	public void setToUserId(long toUserId);

	/**
	 * Returns the to user uuid of this asset message.
	 *
	 * @return the to user uuid of this asset message
	 * @throws SystemException if a system exception occurred
	 */
	public String getToUserUuid() throws SystemException;

	/**
	 * Sets the to user uuid of this asset message.
	 *
	 * @param toUserUuid the to user uuid of this asset message
	 */
	public void setToUserUuid(String toUserUuid);

	/**
	 * Returns the message of this asset message.
	 *
	 * @return the message of this asset message
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this asset message.
	 *
	 * @param message the message of this asset message
	 */
	public void setMessage(String message);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.rivetlogic.assetmanagement.model.AssetMessage assetMessage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.rivetlogic.assetmanagement.model.AssetMessage> toCacheModel();

	@Override
	public com.rivetlogic.assetmanagement.model.AssetMessage toEscapedModel();

	@Override
	public com.rivetlogic.assetmanagement.model.AssetMessage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}