/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.rivetlogic.assetmanagement.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.rivetlogic.assetmanagement.model.AssetMessage;
import com.rivetlogic.assetmanagement.model.AssetMessageModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AssetMessage service. Represents a row in the &quot;rivetlogic_AssetMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.rivetlogic.assetmanagement.model.AssetMessageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetMessageImpl}.
 * </p>
 *
 * @author Manrique Varela
 * @see AssetMessageImpl
 * @see com.rivetlogic.assetmanagement.model.AssetMessage
 * @see com.rivetlogic.assetmanagement.model.AssetMessageModel
 * @generated
 */
public class AssetMessageModelImpl extends BaseModelImpl<AssetMessage>
	implements AssetMessageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset message model instance should use the {@link com.rivetlogic.assetmanagement.model.AssetMessage} interface instead.
	 */
	public static final String TABLE_NAME = "rivetlogic_AssetMessage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "assetMessageId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "assetId", Types.BIGINT },
			{ "fromUserId", Types.BIGINT },
			{ "toUserId", Types.BIGINT },
			{ "message", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table rivetlogic_AssetMessage (uuid_ VARCHAR(75) null,assetMessageId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,assetId LONG,fromUserId LONG,toUserId LONG,message VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table rivetlogic_AssetMessage";
	public static final String ORDER_BY_JPQL = " ORDER BY assetMessage.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY rivetlogic_AssetMessage.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.rivetlogic.assetmanagement.model.AssetMessage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.rivetlogic.assetmanagement.model.AssetMessage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.rivetlogic.assetmanagement.model.AssetMessage"),
			true);
	public static long COMPANYID_COLUMN_BITMASK = 1L;
	public static long GROUPID_COLUMN_BITMASK = 2L;
	public static long UUID_COLUMN_BITMASK = 4L;
	public static long CREATEDATE_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.rivetlogic.assetmanagement.model.AssetMessage"));

	public AssetMessageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetMessageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetMessageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetMessageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetMessage.class;
	}

	@Override
	public String getModelClassName() {
		return AssetMessage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("assetMessageId", getAssetMessageId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("assetId", getAssetId());
		attributes.put("fromUserId", getFromUserId());
		attributes.put("toUserId", getToUserId());
		attributes.put("message", getMessage());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long assetMessageId = (Long)attributes.get("assetMessageId");

		if (assetMessageId != null) {
			setAssetMessageId(assetMessageId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long assetId = (Long)attributes.get("assetId");

		if (assetId != null) {
			setAssetId(assetId);
		}

		Long fromUserId = (Long)attributes.get("fromUserId");

		if (fromUserId != null) {
			setFromUserId(fromUserId);
		}

		Long toUserId = (Long)attributes.get("toUserId");

		if (toUserId != null) {
			setToUserId(toUserId);
		}

		String message = (String)attributes.get("message");

		if (message != null) {
			setMessage(message);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getAssetMessageId() {
		return _assetMessageId;
	}

	@Override
	public void setAssetMessageId(long assetMessageId) {
		_assetMessageId = assetMessageId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public long getAssetId() {
		return _assetId;
	}

	@Override
	public void setAssetId(long assetId) {
		_assetId = assetId;
	}

	@Override
	public long getFromUserId() {
		return _fromUserId;
	}

	@Override
	public void setFromUserId(long fromUserId) {
		_fromUserId = fromUserId;
	}

	@Override
	public String getFromUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getFromUserId(), "uuid", _fromUserUuid);
	}

	@Override
	public void setFromUserUuid(String fromUserUuid) {
		_fromUserUuid = fromUserUuid;
	}

	@Override
	public long getToUserId() {
		return _toUserId;
	}

	@Override
	public void setToUserId(long toUserId) {
		_toUserId = toUserId;
	}

	@Override
	public String getToUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getToUserId(), "uuid", _toUserUuid);
	}

	@Override
	public void setToUserUuid(String toUserUuid) {
		_toUserUuid = toUserUuid;
	}

	@Override
	public String getMessage() {
		if (_message == null) {
			return StringPool.BLANK;
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		_message = message;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			AssetMessage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetMessage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AssetMessage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetMessageImpl assetMessageImpl = new AssetMessageImpl();

		assetMessageImpl.setUuid(getUuid());
		assetMessageImpl.setAssetMessageId(getAssetMessageId());
		assetMessageImpl.setGroupId(getGroupId());
		assetMessageImpl.setCompanyId(getCompanyId());
		assetMessageImpl.setCreateDate(getCreateDate());
		assetMessageImpl.setAssetId(getAssetId());
		assetMessageImpl.setFromUserId(getFromUserId());
		assetMessageImpl.setToUserId(getToUserId());
		assetMessageImpl.setMessage(getMessage());

		assetMessageImpl.resetOriginalValues();

		return assetMessageImpl;
	}

	@Override
	public int compareTo(AssetMessage assetMessage) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), assetMessage.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AssetMessage)) {
			return false;
		}

		AssetMessage assetMessage = (AssetMessage)obj;

		long primaryKey = assetMessage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		AssetMessageModelImpl assetMessageModelImpl = this;

		assetMessageModelImpl._originalUuid = assetMessageModelImpl._uuid;

		assetMessageModelImpl._originalGroupId = assetMessageModelImpl._groupId;

		assetMessageModelImpl._setOriginalGroupId = false;

		assetMessageModelImpl._originalCompanyId = assetMessageModelImpl._companyId;

		assetMessageModelImpl._setOriginalCompanyId = false;

		assetMessageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AssetMessage> toCacheModel() {
		AssetMessageCacheModel assetMessageCacheModel = new AssetMessageCacheModel();

		assetMessageCacheModel.uuid = getUuid();

		String uuid = assetMessageCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			assetMessageCacheModel.uuid = null;
		}

		assetMessageCacheModel.assetMessageId = getAssetMessageId();

		assetMessageCacheModel.groupId = getGroupId();

		assetMessageCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			assetMessageCacheModel.createDate = createDate.getTime();
		}
		else {
			assetMessageCacheModel.createDate = Long.MIN_VALUE;
		}

		assetMessageCacheModel.assetId = getAssetId();

		assetMessageCacheModel.fromUserId = getFromUserId();

		assetMessageCacheModel.toUserId = getToUserId();

		assetMessageCacheModel.message = getMessage();

		String message = assetMessageCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			assetMessageCacheModel.message = null;
		}

		return assetMessageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", assetMessageId=");
		sb.append(getAssetMessageId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", assetId=");
		sb.append(getAssetId());
		sb.append(", fromUserId=");
		sb.append(getFromUserId());
		sb.append(", toUserId=");
		sb.append(getToUserId());
		sb.append(", message=");
		sb.append(getMessage());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.rivetlogic.assetmanagement.model.AssetMessage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assetMessageId</column-name><column-value><![CDATA[");
		sb.append(getAssetMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assetId</column-name><column-value><![CDATA[");
		sb.append(getAssetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fromUserId</column-name><column-value><![CDATA[");
		sb.append(getFromUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>toUserId</column-name><column-value><![CDATA[");
		sb.append(getToUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>message</column-name><column-value><![CDATA[");
		sb.append(getMessage());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = AssetMessage.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			AssetMessage.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _assetMessageId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private Date _createDate;
	private long _assetId;
	private long _fromUserId;
	private String _fromUserUuid;
	private long _toUserId;
	private String _toUserUuid;
	private String _message;
	private long _columnBitmask;
	private AssetMessage _escapedModel;
}