/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.rivetlogic.assetmanagement.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rivetlogic.assetmanagement.model.AssetRequest;
import com.rivetlogic.assetmanagement.service.AssetRequestLocalServiceUtil;

/**
 * The extended model base implementation for the AssetRequest service. Represents a row in the &quot;rivetlogic_AssetRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetRequestImpl}.
 * </p>
 *
 * @author Manrique Varela
 * @see AssetRequestImpl
 * @see com.rivetlogic.assetmanagement.model.AssetRequest
 * @generated
 */
public abstract class AssetRequestBaseImpl extends AssetRequestModelImpl
	implements AssetRequest {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset request model instance should use the {@link AssetRequest} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			AssetRequestLocalServiceUtil.addAssetRequest(this);
		}
		else {
			AssetRequestLocalServiceUtil.updateAssetRequest(this);
		}
	}
}